"""Hardcoded weekly focus and per-lesson goal/task text.

This content must be returned to the user verbatim, never paraphrased or
regenerated by the LLM, so it lives here as plain data and is served through
a code-level override in coach/agent.py (see detect_lesson_goal_request,
detect_week_focus_request, detect_generic_weekly_query).
"""

from typing import Dict

LESSON_GOALS: Dict[int, str] = {
    1: (
        "Go to the \"Goals\" page and choose a \"Suggested Goal\" or create your own physical "
        "activity goal for the week, an aerobic, strength, or balance activity that feels "
        "realistic and enjoyable for you. Lesson 2 becomes available Thursday."
    ),
    2: (
        "Check in on your goal from this week. Go to the \"Goals\" page to mark it complete or "
        "set a new goal before your next lesson."
    ),
    3: (
        "Go to the \"Goals\" page and choose a \"Suggested Goal\" or create your own physical "
        "activity goal for the week, an aerobic, strength, or balance activity that feels "
        "realistic and enjoyable for you. Lesson 4 becomes available Thursday."
    ),
    4: (
        "Check in on your goal from this week. Go to the \"Goals\" page to mark it complete or "
        "set a new goal before your next lesson."
    ),
    5: (
        "Go to the \"Goals\" page and lock in a \"Suggested Goal\" or set a custom goal, keeping "
        "the recommendation of moderate-to-vigorous physical activity per week in mind."
    ),
    6: (
        "Check in on your goal. Go to the \"Goals\" page to mark it complete or set your next "
        "goal, and think about what else you can do this week to reach your "
        "moderate-to-vigorous physical activity goal."
    ),
    7: (
        "Set your next goal. Go to the \"Goals\" page and select a \"Suggested Goal\" or create "
        "one that fits your schedule, ideally working toward the moderate-to-vigorous physical "
        "activity recommendation each week."
    ),
    8: (
        "Go to the \"Goals\" page to mark your goal complete or set your next goal. Reflect on "
        "what else you could do this week to move closer to your moderate-to-vigorous physical "
        "activity goal."
    ),
    9: (
        "Go to the \"Goals\" page and select a Suggested Goal or create a custom goal that fits "
        "your lifestyle, keeping the moderate-to-vigorous physical activity recommendation in "
        "mind."
    ),
    10: (
        "You've completed the core Reframing Retirement lessons. Take a moment to celebrate how "
        "far you've come, the skills, strategies, and habits you've built are tools you can keep "
        "using every day. Keep setting meaningful goals and working toward your "
        "moderate-to-vigorous physical activity goal each week.\n\n"
        "Keep using the Goals page to continue working toward your physical activity "
        "guidelines. Go to the main page."
    ),
}

WEEK_FOCUS: Dict[int, str] = {
    1: "This week's focus: Choose your starting goal. Lessons to complete: 1 and 2.",
    2: "This week's focus: Shape a goal that fits your life. Lessons to complete: 3 and 4.",
    3: "This week's focus: Keep going and notice your progress. Lessons to complete: 5 and 6.",
    4: "This week's focus: Make your goal a habit. Lessons to complete: 7 and 8.",
    5: "This week's focus: Maintain your active lifestyle. Lessons to complete: 9 and 10.",
}

LESSON_TO_WEEK: Dict[int, int] = {
    1: 1, 2: 1,
    3: 2, 4: 2,
    5: 3, 6: 3,
    7: 4, 8: 4,
    9: 5, 10: 5,
}

OUT_OF_RANGE_MESSAGE = (
    "The program only covers Lessons 1-10 across 5 weeks, so that one is outside its scope."
)

CLARIFYING_QUESTION = "Which lesson (or week) number are you currently on?"
